version: "3"
services:
  nginx:
    image: nginx:alpine
    ports: 
      - "8080:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
  php:
    build:
      context: .
      dockerfile: ./docker/php.Dockerfile
    volumes:
      - ./src/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
        - '3306:3306'
    environment:
        MYSQL_ROOT_PASSWORD: 'secret'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: 'example_db'
    volumes:
        - './database:/var/lib/mysql'
